### ISSUE TITLE
Why gravel cracked into sand?

### ISSUE THREAD

**Issue by HoldYourWaffle** [cyanobacterium/BaseMetals#3]
What is the logic of cracking gravel into sand.
Isn't it better to crack gravel into flint?

**Comment by DrPlantabyte** [comment]
Gravel is not usually made of flint, it is just small rocks. Sand is just extremely small rocks. So the logic is this: Stone (large rocks) can be broken into smaller rocks (cobblestone), which can be broken into even smaller rocks (gravel), which can be broken into the smallest rocks possible (sand). If you have my Mineralogy mod installed, then stone gets broken into gravel instead of cobblestone for game balance reasons (Mineralogy stones count as cobblestone in all recipes).

**Comment by HoldYourWaffle** [comment]
Yeah that's quite logic i think.
The only "thing" is that (i think) that there is an difference between "real world logic" and "minecraft logic".
You get flint from gravel if you break it, so it would be logic that if you crack it you get the same.

**Comment by DrPlantabyte** [comment]
There isn't a consensus about this in the Minecraft modding community. Some mods with rock crusher machines do it my way and some do it your way. I've seen people combine crushers from several mods to make a machine that turns cobblestone into TNT (one mod does cobblestone -> gravel -> sand and another mod does cobblestone -> gravel -> flint -> gunpowder).
If you are trying to get a lot of flint, I'd recommend installing another mod that makes it craftable from gravel or obtainable from other sources.

**Comment by HoldYourWaffle** [comment]
That's an nice point.
I think that to behold (is that correct english?) the uniservality (same thing again...) you should make an config option for it, and then gravel->sand as default.

**Comment by DrPlantabyte** [comment]
I'm sorry, but I'm not going to add that feature at this time. There's not much demand for it and I've got other issues to fix.
