### ISSUE TITLE
Possibly of interest for villager trades

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#58]
https://github.com/way2muchnoise/JustEnoughResources/commit/3a5640c5070989a61bb567758fc620d9f205c5f9

**Comment by DrPlantabyte** [comment]
When I last updated, I noticed that Forge had already improved their villager trade API and updated to that (the array hacking code is not used, but not yet deleted):
https://github.com/cyanobacterium/BaseMetals/blob/master/src/main/java/cyano/basemetals/util/VillagerTradeHelper.java#L53

Since I don't add any new villager professions (yet), I think that JER should work fine without needing to make any changes to Base Metals.
