### ISSUE TITLE
Can't disable Iron changes

### ISSUE THREAD

**Issue by MrAmericanMike** [cyanobacterium/BaseMetals#61]
Isn't there an option to disable the changes the mod makes to iron items and blocks?

Would it be possible to remove the Minecraft assets from the mod jar if that's the case?

Thanks a lot.

**Comment by DrPlantabyte** [comment]
It is just a texture in the built-in resource pack for this mod. Since that lies outside the computer code, I cannot use config options to disable it, but installing a texture pack will override the changes.

If it really bothers you, you can also remove the offending textures from the .jar file (delete the assets/minecraft folder). That will also revert the doors to their 2D icons.

**Comment by jriwanek** [comment]
Moved to new tracker
