### ISSUE TITLE
Full TiC Support

### ISSUE THREAD

**Issue by jriwanek** [cyanobacterium/BaseMetals#64]
Will be finishing this for MM before I push it to TiC, depends on #41 before I can do it too.

Should be getting back to submitting soon, I've been on a sorta sabbatical....

**Comment by TyoAtrosa** [comment]
Just posting my suggestions here for you from the other forum:

I have a few ideas for effects and stats if you want to use them:
Invar i think should have a stronger magnetic effect than iron for its effect with a slightly higher bonus durability and handle modifier. Diamond mining level. same damage as iron.

Cold-Iron should keep it's bonus damage against nether mobs as its main effect and have reduced durability loss in hot environments. Obsidian mining level, steel damage level.

Adamantine should have very high base durability and a high handle modifier, and it should have an Unbreaking effect (3 for tool heads/blades, 1 for other parts). Cobalt mining level, steel damage level.

Aquarium i think should have cactus level damage on land but underwater or while flying get a massive damage boost. otherwise bronze durability and diamond mining level.

Mithril: high base durability and enhances other modifiers (fortune 3 becomes fortune 4, bonus fire damage when combined with blaze powder, bonus sharpness when combined with quartz, bonus beheading on cleavers and when combined with beheading, etc). Stone mining level and iron damage, but multiple parts stacks effect (+1 for one part. +2 for three parts).

Star-Steel: Manyullyn mining level, slightly lower damage, high knockback and makes enemies float in midair for a few seconds when used as a blade.

**Comment by TyoAtrosa** [comment]
A few i forgot:

Platinum: Cobalt mining level and high damage, lower base durability but high bonus durability and handle modifier. Shiny!

Mercury: usable as a modifier, adds Wither effect.

**Comment by Zaweri** [comment]
@TyoAtrosa Star-Steel should have autorepair. Also, TiC tools don't have support for certain modifiers in certain places, e.g you can't do "this part gives this effect when it is used as a handle, but it gives another one when used as a head" if my memory serves right.

**Comment by Syndaryl** [comment]
TiC _does_ have support for different modifiers on different parts, at least as of 1.9.4

**Comment by Zaweri** [comment]
@Syndaryl Noticed that the other day, I lied!

**Comment by Keridos** [comment]
Any updates on this? I kind of have a working alpha version of my own compatability mod already, will drop development when this gets official support soonish.

**Comment by jriwanek** [comment]
It's already in my dev builds, I'm just cleaning them up now, won't be too long.

**Comment by Keridos** [comment]
Any news on this?

**Comment by jriwanek** [comment]
Due to the handover from cyano to me things have been rather busy, I've already got the test code for it into Modern Metals, I'm now in the process of moving all the new stuff into Base Metals, It's coming, don't worry.

**Comment by Nikslg** [comment]
Any info about Base Metal Support for TiC2?
It's cool that we can smelt, but having TiC Tools out of those materials would be great.

**Comment by jriwanek** [comment]
It's in dev and still a bit buggy.

**Comment by GazbonicAcid** [comment]
What the current status of TiC support?
Could I have a copy of the dev builds with TiC support purely to play around with that support myself?

**Comment by jriwanek** [comment]
Barring lack of traits, It's mostly done, you can get dev builds from the maven:
https://maven.mcmoddev.com/

**Comment by majix560** [comment]
https://hastebin.com/kokohekibu.md
[Logs.zip](https://github.com/cyanobacterium/BaseMetals/files/663803/Logs.zip)
ModernMetals-1.10.2-0.12.9-beta1.jar 2016-Dec-19
BaseMetals-1.10.2-2.5.0-beta1.jar 2016-Dec-19
I'll try using an updated version of forge and see if that helps slash is the cause.

**Comment by majix560** [comment]
Sorry, I suppose I should have said the dev builds are crashing minecraft for me.

**Comment by GazbonicAcid** [comment]
@jriwanek due to the [Beta Builds crashing](https://github.com/cyanobacterium/BaseMetals/issues/82) I can't play around with this TiC support.

**Comment by jriwanek** [comment]
Oh for fucksakes, For reasons I'm not entirely sure approximately 1 time in around 10 it uploads the deobf jar as the normal jar. I'll upload a replacement.

**Comment by GazbonicAcid** [comment]
@jriwanek you forgot to replace modern metals.
It seems to have happened for both base and modern metals.
Edit: Though the base metals replacement was successful.

**Comment by jriwanek** [comment]
https://github.com/MinecraftModDevelopment/BaseMetals/issues/35
